### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by piscisaureus** [denoland/terraform-provider-deno#10]
Provider: https://registry.terraform.io/providers/denoland/deno/latest/docs

- [ ] Needs an example of how to import and configure the provider 
- [ ] Hide the `host` attribute or move it to the bottom (it has no utility for end users).

Resource: https://registry.terraform.io/providers/denoland/deno/latest/docs/resources/project

- [ ] Missing example
- [ ] Read-only attributes are not in a logical order. Generally, put `id` at the top and `created_at`/`updated_at` at the bottom.
- [ ] Date attributes should mention the format (e.g. RFC3339)

Resource: https://registry.terraform.io/providers/denoland/deno/latest/docs/resources/deployment

- [ ] Missing example(s). Preferrably we should have one example that uses in-line file content and another one that uses the `deno_assets` data source.
- [ ] `status` attributes: mention possible values
- [ ] `env_vars` is a required attribute in the API, but not in the schema. Is this intentional?
- [ ] In the documentation for `Assets`:
  - [ ] Lacks explanation
  - [ ] Possible enum values for `kind` should be documented.
  - [ ] `content` and `encoding` are not documented.
  - [ ] `size` attribute: this is not a concept in the API, what's the purpose of it? I would suggest removing in.
  - [ ] Is it possible to use the same schema for `assets` and `uploaded_assets`?

Resource: https://registry.terraform.io/providers/denoland/deno/latest/docs/resources/domain

- [ ] Missing example: show the setup required to link a domain to an organization, verify it and provision certificates.

Resource: https://registry.terraform.io/providers/denoland/deno/latest/docs/resources/certificate_provisioning

- [ ] Add a reference to the `domain` resource example in the documentation.
- [ ] `provisioning_status`: mention possible values
- [ ] Should have a `timeouts` attribute?

Resource: https://registry.terraform.io/providers/denoland/deno/latest/docs/resources/domain_verification

- [ ] Add a reference to the `domain` resource example in the documentation.

Data source: https://registry.terraform.io/providers/denoland/deno/latest/docs/data-sources/assets

- [ ] Add a reference to the `deno_deployment` resource example in the documentation.

Data source: https://registry.terraform.io/providers/denoland/deno/latest/docs/data-sources/organization

- [ ] Missing example
- [ ] `id` attribute is missing

**Comment by magurotuna** [comment]
Regarding the order of fields in the document: it seems like there's no option allowing us to control the rendering order, it's simply ordered alphabetically.
