### ISSUE TITLE
Rework on how `deno_assets` and `deno_deployment` work together

### ISSUE THREAD

**Issue by magurotuna** [denoland/terraform-provider-deno#11]
Currently, `deno_assets` collects assets metadata (note here that the actual content is not collected) based on the glob pattern configured by the user. The collected data is intended to be passed to `deno_deployment`. 

The problem with this approach is that it's very hard to use `deno_deployment` without the support of `deno_assets`. In particular, specifying assets inline in the `deno_deployment` resource configuration is unnecessarily complicated since it requires the file content to be hashed. 

One possible solution for this is simply to fix `deno_assets` so it collects file contents as well. This also means that `deno_deployment` will also be fixed to take file contents instead of hash, thus inlining assets will get a lot easier. Actually, I did think about this approach when I developed `deno_assets`, but I didn't adopt because I was unsure if this approach would cause terraform state to become very huge. If this is not such a problem, we can go with it.

Another way would be to introduce another data source, let's say `deno_inline_assets`, that allows to define inlined assets in a terraform file. This will convert the inlined assets into the format that can be passed to `deno_deployment`.

**Comment by piscisaureus** [comment]
Fixed: #28

**Comment by magurotuna** [comment]
Closing as fixed
